// src/app/components/json-viewer/json-viewer.component.ts
import { Component, Input } from "@angular/core"

@Component({
  selector: "app-json-viewer",
  templateUrl: "./json-viewer.component.html",
  styleUrls: ["./json-viewer.component.css"],
})
export class JsonViewerComponent {
  @Input() data: any

  get jsonString(): string {
    return JSON.stringify(this.data, null, 2)
  }
}

<div class="json-viewer">
  <pre class="json-pre"><code class="json-code">{{ jsonString }}</code></pre>
</div>

// components/json-viewer.tsx
"use client"

interface JsonViewerProps {
  data: any
}

export function JsonViewer({ data }: JsonViewerProps) {
  const jsonString = JSON.stringify(data, null, 2)

  return (
    <div className="json-viewer">
      <pre className="json-pre">
        <code className="json-code">{jsonString}</code>
      </pre>
    </div>
  )
}
