// src/app/components/json-modal/json-modal.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core"

@Component({
  selector: "app-json-modal",
  templateUrl: "./json-modal.component.html",
  styleUrls: ["./json-modal.component.css"],
})
export class JsonModalComponent {
  @Input() data: any
  @Input() title = "JSON Data"
  @Output() close = new EventEmitter<void>()

  onClose(): void {
    this.close.emit()
  }

  onBackdropClick(event: MouseEvent): void {
    if (event.target === event.currentTarget) {
      this.onClose()
    }
  }

  copyToClipboard(): void {
    const jsonString = JSON.stringify(this.data, null, 2)
    navigator.clipboard.writeText(jsonString).then(() => {
      alert("JSON copied to clipboard!")
    })
  }
}

<div class="modal-backdrop" (click)="onBackdropClick($event)">
  <div class="modal-content">
    <div class="modal-header">
      <h2 class="modal-title">{{ title }}</h2>
      <div class="modal-actions">
        <button class="copy-btn" (click)="copyToClipboard()">
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
            <path d="M5.5 4.5V3.5C5.5 2.94772 5.94772 2.5 6.5 2.5H12.5C13.0523 2.5 13.5 2.94772 13.5 3.5V9.5C13.5 10.0523 13.0523 10.5 12.5 10.5H11.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
            <rect x="2.5" y="5.5" width="7" height="8" rx="1" stroke="currentColor" stroke-width="1.5"/>
          </svg>
          Copy
        </button>
        <button class="modal-close" (click)="onClose()">
          <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
            <path d="M15 5L5 15M5 5L15 15" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
          </svg>
        </button>
      </div>
    </div>

    <div class="modal-body">
      <app-json-viewer [data]="data"></app-json-viewer>
    </div>
  </div>
</div>

// components/json-modal.tsx
"use client"

import { useState } from "react"
import { JsonViewer } from "./json-viewer"
import "./json-modal.css"
import "./json-viewer.css"

interface JsonModalProps {
  title: string
  data: any
  isOpen: boolean
  onClose: () => void
  type: "request" | "response"
}

export function JsonModal({ title, data, isOpen, onClose, type }: JsonModalProps) {
  const [copied, setCopied] = useState(false)

  if (!isOpen) return null

  const copyToClipboard = async () => {
    await navigator.clipboard.writeText(JSON.stringify(data, null, 2))
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <>
      <div className="json-modal-backdrop" onClick={onClose} />

      <div className="json-modal-container">
        <div className="json-modal">
          <div className="json-modal-header">
            <div className="json-modal-title-wrapper">
              <span
                className={`json-modal-indicator ${type === "request" ? "indicator-request" : "indicator-response"}`}
              ></span>
              <h2 className="json-modal-title">{title}</h2>
            </div>
            <div className="json-modal-actions">
              <button className="json-modal-button" onClick={copyToClipboard}>
                {copied ? (
                  <svg className="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <polyline points="20 6 9 17 4 12"></polyline>
                  </svg>
                ) : (
                  <svg className="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                    <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
                  </svg>
                )}
                <span className="button-text">{copied ? "Copied!" : "Copy"}</span>
              </button>
              <button className="json-modal-button" onClick={onClose}>
                <svg className="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <line x1="18" y1="6" x2="6" y2="18"></line>
                  <line x1="6" y1="6" x2="18" y2="18"></line>
                </svg>
              </button>
            </div>
          </div>

          <div className="json-modal-content">
            <JsonViewer data={data} />
          </div>
        </div>
      </div>
    </>
  )
}
