// src/app/components/log-modal/log-modal.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core"
import type { LogEntry } from "../../models/log.model"

@Component({
  selector: "app-log-modal",
  templateUrl: "./log-modal.component.html",
  styleUrls: ["./log-modal.component.css"],
})
export class LogModalComponent {
  @Input() log!: LogEntry
  @Input() isChild = false
  @Output() close = new EventEmitter<void>()
  @Output() openJson = new EventEmitter<{ data: any; title: string }>()

  activeTab: "overview" | "request" | "response" = "overview"

  onClose(): void {
    this.close.emit()
  }

  onBackdropClick(event: MouseEvent): void {
    if (event.target === event.currentTarget) {
      this.onClose()
    }
  }

  setActiveTab(tab: "overview" | "request" | "response"): void {
    this.activeTab = tab
  }

  viewRequestJson(): void {
    this.openJson.emit({ data: this.log.request, title: "Request Body" })
  }

  viewResponseJson(): void {
    this.openJson.emit({ data: this.log.response, title: "Response Body" })
  }

  getMethodClass(method: string): string {
    const methodMap: Record<string, string> = {
      GET: "method-get",
      POST: "method-post",
      PUT: "method-put",
      DELETE: "method-delete",
      PATCH: "method-patch",
    }
    return methodMap[method] || ""
  }

  getStatusClass(status: number): string {
    if (status >= 200 && status < 300) return "status-success"
    if (status >= 300 && status < 400) return "status-redirect"
    if (status >= 400 && status < 500) return "status-client-error"
    if (status >= 500) return "status-server-error"
    return ""
  }

  getObjectKeys(obj: any): string[] {
    return obj ? Object.keys(obj) : []
  }
}

import { Component, Input, Output, EventEmitter } from '@angular/core';
import { LogEntry, JsonModalData } from '../../models/log.model';

@Component({
  selector: 'app-log-modal',
  templateUrl: './log-modal.component.html',
  styleUrls: ['./log-modal.component.css']
})
export class LogModalComponent {
  @Input() log!: LogEntry;
  @Input() isOpen: boolean = false;
  @Output() onClose = new EventEmitter<void>();
  @Output() onOpenJson = new EventEmitter<JsonModalData>();

  jsonModalData: JsonModalData | null = null;

  close() {
    this.onClose.emit();
  }

  onBackdropClick(event: MouseEvent) {
    if (event.target === event.currentTarget) {
      this.close();
    }
  }

  viewRequest(log: LogEntry) {
    this.onOpenJson.emit({
      type: 'request',
      data: log.request,
      title: `${log.endpoint} - Request`
    });
  }

  viewResponse(log: LogEntry) {
    this.onOpenJson.emit({
      type: 'response',
      data: log.response,
      title: `${log.endpoint} - Response`
    });
  }

  getStatusIcon(status: number, endpoint: string): string {
    // Custom logic based on your requirements
    if (status === 200) return '✓';
    if (endpoint.includes('db')) return '●';
    return '➢';
  }

  getStatusIconClass(status: number, endpoint: string): string {
    if (status === 200) return 'status-success';
    if (endpoint.includes('db')) return 'status-pending';
    return 'status-running';
  }

  getMethodClass(method: string): string {
    const methodMap: Record<string, string> = {
      GET: 'method-get',
      POST: 'method-post',
      PUT: 'method-put',
      DELETE: 'method-delete',
      PATCH: 'method-patch'
    };
    return methodMap[method] || 'method-get';
  }

  countAllChildren(entry: LogEntry): number {
    if (!entry.children || entry.children.length === 0) return 0;
    return entry.children.reduce((acc, child) => acc + 1 + this.countAllChildren(child), 0);
  }

  get totalChildren(): number {
    return this.countAllChildren(this.log);
  }

  toggleChildExpansion(child: LogEntry) {
    child.expanded = !child.expanded;
  }
}

<div class="modal-backdrop" (click)="onBackdropClick($event)">
  <div class="modal-content">
    <div class="modal-header">
      <div>
        <h2 class="modal-title">{{ isChild ? 'Child Operation' : 'Request Log' }} Details</h2>
        <p class="modal-subtitle">{{ log.endpoint }}</p>
      </div>
      <button class="modal-close" (click)="onClose()">
        <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
          <path d="M15 5L5 15M5 5L15 15" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
        </svg>
      </button>
    </div>

    <div class="modal-tabs">
      <button 
        class="modal-tab"
        [class.modal-tab-active]="activeTab === 'overview'"
        (click)="setActiveTab('overview')"
      >
        Overview
      </button>
      <button 
        class="modal-tab"
        [class.modal-tab-active]="activeTab === 'request'"
        (click)="setActiveTab('request')"
      >
        Request
      </button>
      <button 
        class="modal-tab"
        [class.modal-tab-active]="activeTab === 'response'"
        (click)="setActiveTab('response')"
      >
        Response
      </button>
    </div>

    <div class="modal-body">
      <div *ngIf="activeTab === 'overview'" class="tab-content">
        <div class="info-grid">
          <div class="info-item">
            <span class="info-label">ID</span>
            <span class="info-value">{{ log.id }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">Endpoint</span>
            <span class="info-value info-value-code">{{ log.endpoint }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">Method</span>
            <span class="method-badge" [ngClass]="getMethodClass(log.method)">
              {{ log.method }}
            </span>
          </div>
          <div class="info-item">
            <span class="info-label">Status</span>
            <span class="status-badge" [ngClass]="getStatusClass(log.status)">
              {{ log.status }}
            </span>
          </div>
          <div class="info-item">
            <span class="info-label">Timestamp</span>
            <span class="info-value">{{ log.timestamp }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">Duration</span>
            <span class="info-value">{{ log.duration }}ms</span>
          </div>
        </div>

        <div *ngIf="log.headers" class="section">
          <h3 class="section-title">Headers</h3>
          <div class="key-value-list">
            <div *ngFor="let key of getObjectKeys(log.headers)" class="key-value-item">
              <span class="key">{{ key }}:</span>
              <span class="value">{{ log.headers![key] }}</span>
            </div>
          </div>
        </div>

        <div *ngIf="log.queryParams" class="section">
          <h3 class="section-title">Query Parameters</h3>
          <div class="key-value-list">
            <div *ngFor="let key of getObjectKeys(log.queryParams)" class="key-value-item">
              <span class="key">{{ key }}:</span>
              <span class="value">{{ log.queryParams![key] }}</span>
            </div>
          </div>
        </div>
      </div>

      <div *ngIf="activeTab === 'request'" class="tab-content">
        <div class="json-section">
          <div class="json-header">
            <h3 class="section-title">Request Body</h3>
            <button *ngIf="log.request" class="view-json-btn" (click)="viewRequestJson()">
              View Full JSON
            </button>
          </div>
          <app-json-viewer *ngIf="log.request" [data]="log.request"></app-json-viewer>
          <p *ngIf="!log.request" class="empty-message">No request body</p>
        </div>
      </div>

      <div *ngIf="activeTab === 'response'" class="tab-content">
        <div class="json-section">
          <div class="json-header">
            <h3 class="section-title">Response Body</h3>
            <button *ngIf="log.response" class="view-json-btn" (click)="viewResponseJson()">
              View Full JSON
            </button>
          </div>
          <app-json-viewer *ngIf="log.response" [data]="log.response"></app-json-viewer>
          <p *ngIf="!log.response" class="empty-message">No response body</p>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="modal-backdrop" (click)="onBackdropClick($event)">
  <div class="modal-content">
    <!-- header -->
    <div class="modal-header">
      <div class="modal-header-left">
        <h2 class="modal-title">Log Details</h2>
        <p class="modal-subtitle">{{ log?.endpoint }}</p>
      </div>

      <div class="modal-header-meta">
        <span class="meta-item">{{ log?.timestamp }}</span>
        <span class="meta-item method-badge-inline" [ngClass]="getMethodClass(log?.method)">{{ log?.method }}</span>
        <span class="meta-item status-badge-inline" [ngClass]="getStatusClass(log?.status)">{{ log?.status }}</span>
        <span class="meta-item">{{ log?.duration }}ms</span>
        <button class="modal-close" (click)="onClose()" aria-label="Close">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none">
            <path d="M18 6L6 18M6 6L18 18" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
          </svg>
        </button>
      </div>
    </div>

    <!-- tabs -->
    <div class="modal-tabs">
      <button class="modal-tab" [class.modal-tab-active]="activeTab==='overview'" (click)="setActiveTab('overview')">Overview</button>
      <button class="modal-tab" [class.modal-tab-active]="activeTab==='request'" (click)="setActiveTab('request')">Request</button>
      <button class="modal-tab" [class.modal-tab-active]="activeTab==='response'" (click)="setActiveTab('response')">Response</button>
    </div>

    <!-- body -->
    <div class="modal-body">
      <!-- OVERVIEW TAB -->
      <div *ngIf="activeTab === 'overview'" class="tab-content">
        <div class="info-grid">
          <div class="info-item">
            <span class="info-label">ID</span>
            <span class="info-value">{{ log?.id }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">Endpoint</span>
            <span class="info-value info-value-code">{{ log?.endpoint }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">Method</span>
            <span class="info-value"><span class="method-badge" [ngClass]="getMethodClass(log?.method)">{{ log?.method }}</span></span>
          </div>
          <div class="info-item">
            <span class="info-label">Status</span>
            <span class="info-value"><span class="status-badge" [ngClass]="getStatusClass(log?.status)">{{ log?.status }}</span></span>
          </div>
          <div class="info-item">
            <span class="info-label">Timestamp</span>
            <span class="info-value">{{ log?.timestamp }}</span>
          </div>
          <div class="info-item">
            <span class="info-label">Duration</span>
            <span class="info-value">{{ log?.duration }}ms</span>
          </div>
        </div>

        <div *ngIf="log?.headers" class="section">
          <h3 class="section-title">Headers</h3>
          <div class="key-value-list">
            <div *ngFor="let key of getObjectKeys(log.headers)" class="key-value-item">
              <span class="key">{{ key }}:</span>
              <span class="value">{{ log.headers[key] }}</span>
            </div>
          </div>
        </div>

        <div *ngIf="log?.queryParams" class="section">
          <h3 class="section-title">Query Parameters</h3>
          <div class="key-value-list">
            <div *ngFor="let key of getObjectKeys(log.queryParams)" class="key-value-item">
              <span class="key">{{ key }}:</span>
              <span class="value">{{ log.queryParams[key] }}</span>
            </div>
          </div>
        </div>

        <!-- parent actions -->
        <div class="log-parent-actions section">
          <div class="log-section-actions">
            <button class="log-action-button" (click)="viewRequestJson(log); $event.stopPropagation()">
              <span class="action-indicator indicator-request"></span> View Request
            </button>
            <button class="log-action-button" (click)="viewResponseJson(log); $event.stopPropagation()">
              <span class="action-indicator indicator-response"></span> View Response
            </button>
          </div>
        </div>

        <!-- children list -->
        <div *ngIf="log?.children?.length" class="log-children-section">
          <h3 class="log-children-title">
            <span class="children-indicator"></span>
            Child Operations ({{ countAllChildren(log) }} total)
          </h3>

          <div class="log-children-container">
            <!-- recursive template for nested items -->
            <ng-template #nested let-entry let-level="level">
              <div class="nested-log-item" [style.border-left-width.px]="level > 0 ? level * 2 : 0" [style.border-left-color]="'#e5e7eb'">
                <button
                  class="nested-log-header"
                  (click)="toggleExpanded(entry.id)"
                  [style.paddingLeft.px]="16 + level * 16"
                >
                  <div class="nested-log-chevron">
                    <svg *ngIf="isExpanded(entry.id)" class="chev" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                      <polyline points="6 9 12 15 18 9" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></polyline>
                    </svg>
                    <svg *ngIf="!isExpanded(entry.id)" class="chev" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                      <polyline points="9 18 15 12 9 6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></polyline>
                    </svg>
                  </div>

                  <div class="nested-log-info">
                    <span class="nested-log-timestamp">{{ entry.timestamp }}</span>
                    <span class="nested-log-endpoint">{{ entry.endpoint }}</span>
                    <span class="nested-log-method" [ngClass]="getMethodClass(entry.method)">{{ entry.method }}</span>
                    <span class="nested-log-status" [ngClass]="getStatusClass(entry.status)">{{ entry.status }}</span>
                    <span class="nested-log-duration">{{ entry.duration }}ms</span>
                  </div>

                  <div class="nested-log-right">
                    <span *ngIf="entry.children?.length" class="nested-log-count">+{{ entry.children.length }}</span>
                  </div>
                </button>

                <div *ngIf="isExpanded(entry.id)" class="nested-log-expanded" [style.paddingLeft.px]="16 + level * 16">
                  <div class="nested-log-actions">
                    <button class="log-action-button" (click)="viewRequestJson(entry); $event.stopPropagation()">
                      <span class="action-indicator indicator-request"></span> View Request
                    </button>
                    <button class="log-action-button" (click)="viewResponseJson(entry); $event.stopPropagation()">
                      <span class="action-indicator indicator-response"></span> View Response
                    </button>
                  </div>

                  <div *ngIf="entry.children?.length" class="nested-children-container">
                    <ng-container *ngFor="let child of entry.children">
                      <ng-container *ngTemplateOutlet="nested; context: { $implicit: child, level: level + 1 }"></ng-container>
                    </ng-container>
                  </div>
                </div>
              </div>
            </ng-template>

            <!-- initial render with level 0 -->
            <ng-container *ngFor="let child of log.children">
              <ng-container *ngTemplateOutlet="nested; context: { $implicit: child, level: 0 }"></ng-container>
            </ng-container>
          </div>
        </div>
      </div>

      <!-- REQUEST TAB -->
      <div *ngIf="activeTab === 'request'" class="tab-content">
        <div class="json-section">
          <div class="json-header">
            <h3 class="section-title">Request Body</h3>
            <button *ngIf="log.request" class="view-json-btn" (click)="viewRequestJson(log)">View Full JSON</button>
          </div>
          <app-json-viewer *ngIf="log.request" [data]="log.request"></app-json-viewer>
          <p *ngIf="!log.request" class="empty-message">No request body</p>
        </div>
      </div>

      <!-- RESPONSE TAB -->
      <div *ngIf="activeTab === 'response'" class="tab-content">
        <div class="json-section">
          <div class="json-header">
            <h3 class="section-title">Response Body</h3>
            <button *ngIf="log.response" class="view-json-btn" (click)="viewResponseJson(log)">View Full JSON</button>
          </div>
          <app-json-viewer *ngIf="log.response" [data]="log.response"></app-json-viewer>
          <p *ngIf="!log.response" class="empty-message">No response body</p>
        </div>
      </div>
    </div>
  </div>
</div>

// components/log-modal.tsx
"use client"

import { useState } from "react"
import { JsonModal } from "./json-modal"
import type { LogEntry } from "./log-viewer"
import "./log-modal.css"

interface LogModalProps {
  log: LogEntry
  isOpen: boolean
  onClose: () => void
}

interface NestedLogItemProps {
  child: LogEntry
  level: number
}

function NestedLogItem({ child, level }: NestedLogItemProps) {
  const [isExpanded, setIsExpanded] = useState(false)
  const [jsonModal, setJsonModal] = useState<{ type: "request" | "response"; data: any } | null>(null)

  const getStatusBadgeClass = (status: number) => {
    if (status >= 200 && status < 300) return "status-success"
    if (status >= 400 && status < 500) return "status-warning"
    if (status >= 500) return "status-error"
    return "status-info"
  }

  const getMethodClass = (method: string) => {
    const methodMap: Record<string, string> = {
      GET: "method-get",
      POST: "method-post",
      PUT: "method-put",
      DELETE: "method-delete",
      PATCH: "method-patch",
    }
    return methodMap[method] || "method-get"
  }

  const borderLeftWidth = level > 0 ? `${level * 2}px` : "0px"

  return (
    <>
      <div className="nested-log-item" style={{ borderLeftWidth, borderLeftColor: "#e5e7eb" }}>
        <button
          onClick={() => setIsExpanded(!isExpanded)}
          className="nested-log-header"
          style={{ paddingLeft: `${16 + level * 16}px` }}
        >
          <div className="nested-log-chevron">
            {isExpanded ? (
              <svg className="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <polyline points="6 9 12 15 18 9"></polyline>
              </svg>
            ) : (
              <svg className="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <polyline points="9 18 15 12 9 6"></polyline>
              </svg>
            )}
          </div>

          <div className="nested-log-info">
            <span className="nested-log-timestamp">{child.timestamp}</span>
            <span className="nested-log-endpoint">{child.endpoint}</span>
            <span className={`nested-log-method ${getMethodClass(child.method)}`}>{child.method}</span>
            <span className={`nested-log-status ${getStatusBadgeClass(child.status)}`}>{child.status}</span>
            <span className="nested-log-duration">{child.duration}ms</span>
          </div>

          {child.children && child.children.length > 0 && (
            <span className="nested-log-count">+{child.children.length}</span>
          )}
        </button>

        {isExpanded && (
          <div className="nested-log-expanded" style={{ paddingLeft: `${16 + level * 16}px` }}>
            <div className="nested-log-actions">
              <button
                className="log-action-button"
                onClick={(e) => {
                  e.stopPropagation()
                  setJsonModal({ type: "request", data: child.request })
                }}
              >
                <span className="action-indicator indicator-request"></span>
                View Request
              </button>
              <button
                className="log-action-button"
                onClick={(e) => {
                  e.stopPropagation()
                  setJsonModal({ type: "response", data: child.response })
                }}
              >
                <span className="action-indicator indicator-response"></span>
                View Response
              </button>
            </div>

            {child.children && child.children.length > 0 && (
              <div className="nested-children-container">
                {child.children.map((nestedChild) => (
                  <NestedLogItem key={nestedChild.id} child={nestedChild} level={level + 1} />
                ))}
              </div>
            )}
          </div>
        )}
      </div>

      {jsonModal && (
        <JsonModal
          title={`${child.endpoint} - ${jsonModal.type === "request" ? "Request" : "Response"}`}
          data={jsonModal.data}
          isOpen={true}
          onClose={() => setJsonModal(null)}
          type={jsonModal.type}
        />
      )}
    </>
  )
}

export function LogModal({ log, isOpen, onClose }: LogModalProps) {
  const [jsonModal, setJsonModal] = useState<{ type: "request" | "response"; data: any } | null>(null)

  if (!isOpen) return null

  const getStatusBadgeClass = (status: number) => {
    if (status >= 200 && status < 300) return "status-success"
    if (status >= 400 && status < 500) return "status-warning"
    if (status >= 500) return "status-error"
    return "status-info"
  }

  const getMethodClass = (method: string) => {
    const methodMap: Record<string, string> = {
      GET: "method-get",
      POST: "method-post",
      PUT: "method-put",
      DELETE: "method-delete",
      PATCH: "method-patch",
    }
    return methodMap[method] || "method-get"
  }

  const countAllChildren = (entry: LogEntry): number => {
    if (!entry.children || entry.children.length === 0) return 0
    return entry.children.reduce((acc, child) => acc + 1 + countAllChildren(child), 0)
  }

  const totalChildren = countAllChildren(log)

  return (
    <>
      <div className="log-modal-backdrop" onClick={onClose} />

      <div className="log-modal-container">
        <div className="log-modal">
          <div className="log-modal-header">
            <div className="log-modal-header-content">
              <h2 className="log-modal-title">Log Details</h2>
              <div className="log-modal-meta">
                <span className="log-meta-timestamp">{log.timestamp}</span>
                <span className={`log-meta-method ${getMethodClass(log.method)}`}>{log.method}</span>
                <span className="log-meta-endpoint">{log.endpoint}</span>
                <span className={`log-meta-status ${getStatusBadgeClass(log.status)}`}>{log.status}</span>
                <span className="log-meta-duration">{log.duration}ms</span>
              </div>
            </div>
            <button className="log-modal-close" onClick={onClose}>
              <svg className="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <line x1="18" y1="6" x2="6" y2="18"></line>
                <line x1="6" y1="6" x2="18" y2="18"></line>
              </svg>
            </button>
          </div>

          <div className="log-modal-content">
            <div className="log-modal-section">
              <h3 className="log-section-title">Parent Log Data</h3>
              <div className="log-section-actions">
                <button
                  className="log-action-button"
                  onClick={() => setJsonModal({ type: "request", data: log.request })}
                >
                  <span className="action-indicator indicator-request"></span>
                  View Request
                </button>
                <button
                  className="log-action-button"
                  onClick={() => setJsonModal({ type: "response", data: log.response })}
                >
                  <span className="action-indicator indicator-response"></span>
                  View Response
                </button>
              </div>
            </div>

            {log.children && log.children.length > 0 && (
              <div className="log-children-section">
                <h3 className="log-children-title">
                  <span className="children-indicator"></span>
                  Child Operations ({totalChildren} total)
                </h3>
                <div className="log-children-container">
                  {log.children.map((child) => (
                    <NestedLogItem key={child.id} child={child} level={0} />
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {jsonModal && (
        <JsonModal
          title={`${log.endpoint} - ${jsonModal.type === "request" ? "Request" : "Response"}`}
          data={jsonModal.data}
          isOpen={true}
          onClose={() => setJsonModal(null)}
          type={jsonModal.type}
        />
      )}
    </>
  )
}
