// src/app/components/log-viewer/log-viewer.component.ts
import { Component, type OnInit, type OnDestroy } from "@angular/core"
import { Subject, combineLatest } from "rxjs"
import { takeUntil, map } from "rxjs/operators"
import type { LogService } from "../../services/log.service"
import type { LogEntry, LogStats } from "../../models/log.model"

@Component({
  selector: "app-log-viewer",
  templateUrl: "./log-viewer.component.html",
  styleUrls: ["./log-viewer.component.css"],
})
export class LogViewerComponent implements OnInit, OnDestroy {
  logs: LogEntry[] = []
  filteredLogs: LogEntry[] = []
  stats: LogStats = { parentLogs: 0, childOperations: 0, filtered: 0 }
  searchQuery = ""
  expandedLogs = new Set<number>()
  selectedLog: LogEntry | null = null
  selectedChild: LogEntry | null = null
  showJsonModal = false
  jsonModalData: any = null
  jsonModalTitle = ""

  private destroy$ = new Subject<void>()

  constructor(private logService: LogService) {}

  ngOnInit(): void {
    combineLatest([this.logService.logs$, this.logService.searchQuery$])
      .pipe(
        takeUntil(this.destroy$),
        map(([logs, query]) => {
          this.logs = logs
          this.searchQuery = query
          return this.logService.filterLogs(logs, query)
        }),
      )
      .subscribe((filtered) => {
        this.filteredLogs = filtered
        this.stats = this.logService.getStats(filtered)
      })
  }

  ngOnDestroy(): void {
    this.destroy$.next()
    this.destroy$.complete()
  }

  onSearchChange(event: Event): void {
    const query = (event.target as HTMLInputElement).value
    this.logService.setSearchQuery(query)
  }

  toggleExpand(logId: number, event: Event): void {
    event.stopPropagation()
    if (this.expandedLogs.has(logId)) {
      this.expandedLogs.delete(logId)
    } else {
      this.expandedLogs.add(logId)
    }
  }

  isExpanded(logId: number): boolean {
    return this.expandedLogs.has(logId)
  }

  isHighlighted(logId: number): boolean {
    return this.expandedLogs.has(logId) || this.selectedLog?.id === logId
  }

  openLogModal(log: LogEntry, event: Event): void {
    event.stopPropagation()
    this.selectedLog = log
    this.selectedChild = null
  }

  openChildModal(parent: LogEntry, child: LogEntry, event: Event): void {
    event.stopPropagation()
    this.selectedLog = parent
    this.selectedChild = child
  }

  closeLogModal(): void {
    this.selectedLog = null
    this.selectedChild = null
  }

  openJsonModal(data: any, title: string): void {
    this.jsonModalData = data
    this.jsonModalTitle = title
    this.showJsonModal = true
  }

  closeJsonModal(): void {
    this.showJsonModal = false
    this.jsonModalData = null
    this.jsonModalTitle = ""
  }

  getMethodClass(method: string): string {
    const methodMap: Record<string, string> = {
      GET: "method-get",
      POST: "method-post",
      PUT: "method-put",
      DELETE: "method-delete",
      PATCH: "method-patch",
    }
    return methodMap[method] || ""
  }

  getStatusClass(status: number): string {
    if (status >= 200 && status < 300) return "status-success"
    if (status >= 300 && status < 400) return "status-redirect"
    if (status >= 400 && status < 500) return "status-client-error"
    if (status >= 500) return "status-server-error"
    return ""
  }
}

<div class="log-viewer">
  <div class="log-header">
    <h1 class="log-title">Request Logs</h1>
    <p class="log-subtitle">Monitor and investigate API request/response logs</p>
  </div>

  <div class="search-container">
    <svg class="search-icon" width="16" height="16" viewBox="0 0 16 16" fill="none">
      <path d="M7 12C9.76142 12 12 9.76142 12 7C12 4.23858 9.76142 2 7 2C4.23858 2 2 4.23858 2 7C2 9.76142 4.23858 12 7 12Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
      <path d="M14 14L10.5 10.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
    <input
      type="text"
      class="search-input"
      placeholder="Search by ID, endpoint, method, or status..."
      [value]="searchQuery"
      (input)="onSearchChange($event)"
    />
  </div>

  <div class="stats-bar">
    <span class="stat-item">
      <strong>{{ stats.parentLogs }}</strong> parent logs
    </span>
    <span class="stat-item">
      <strong>{{ stats.childOperations }}</strong> child operations
    </span>
    <span class="stat-item">
      <strong>{{ stats.filtered }}</strong> filtered
    </span>
  </div>

  <div class="logs-list">
    <div *ngFor="let log of filteredLogs" class="log-group">
      <div 
        class="log-item"
        [class.log-item-highlighted]="isHighlighted(log.id)"
        (click)="openLogModal(log, $event)"
      >
        <button 
          class="log-chevron"
          [class.log-chevron-expanded]="isExpanded(log.id)"
          [class.log-chevron-hidden]="!log.children || log.children.length === 0"
          (click)="toggleExpand(log.id, $event)"
        >
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
            <path d="M6 4L10 8L6 12" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
        </button>

        <div class="log-content">
          <div class="log-endpoint">{{ log.endpoint }}</div>
          
          <div class="log-details">
            <span class="log-detail">
              <span class="log-label">ID:</span>
              <span class="log-value">{{ log.id }}</span>
            </span>
            
            <span class="log-detail">
              <span class="log-label">Time:</span>
              <span class="log-value">{{ log.timestamp }}</span>
            </span>
            
            <span class="log-detail">
              <span class="log-label">Method:</span>
              <span class="method-badge" [ngClass]="getMethodClass(log.method)">
                {{ log.method }}
              </span>
            </span>
            
            <span class="log-detail">
              <span class="log-label">Status:</span>
              <span class="status-badge" [ngClass]="getStatusClass(log.status)">
                {{ log.status }}
              </span>
            </span>
            
            <span class="log-detail">
              <span class="log-label">Duration:</span>
              <span class="log-value">{{ log.duration }}ms</span>
            </span>
          </div>

          <div *ngIf="log.children && log.children.length > 0" class="child-count">
            {{ log.children.length }} child operations
          </div>
        </div>
      </div>

      <div *ngIf="isExpanded(log.id) && log.children && log.children.length > 0" class="children-container">
        <div *ngFor="let child of log.children" class="child-log-wrapper">
          <div 
            class="log-item log-item-child"
            [class.log-item-highlighted]="selectedLog?.id === log.id && selectedChild?.id === child.id"
            (click)="openChildModal(log, child, $event)"
          >
            <div class="log-content">
              <div class="log-endpoint">{{ child.endpoint }}</div>
              
              <div class="log-details">
                <span class="log-detail">
                  <span class="log-label">ID:</span>
                  <span class="log-value">{{ child.id }}</span>
                </span>
                
                <span class="log-detail">
                  <span class="log-label">Time:</span>
                  <span class="log-value">{{ child.timestamp }}</span>
                </span>
                
                <span class="log-detail">
                  <span class="log-label">Method:</span>
                  <span class="method-badge" [ngClass]="getMethodClass(child.method)">
                    {{ child.method }}
                  </span>
                </span>
                
                <span class="log-detail">
                  <span class="log-label">Status:</span>
                  <span class="status-badge" [ngClass]="getStatusClass(child.status)">
                    {{ child.status }}
                  </span>
                </span>
                
                <span class="log-detail">
                  <span class="log-label">Duration:</span>
                  <span class="log-value">{{ child.duration }}ms</span>
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<app-log-modal
  *ngIf="selectedLog"
  [log]="selectedChild || selectedLog"
  [isChild]="!!selectedChild"
  (close)="closeLogModal()"
  (openJson)="openJsonModal($event.data, $event.title)"
></app-log-modal>

<app-json-modal
  *ngIf="showJsonModal"
  [data]="jsonModalData"
  [title]="jsonModalTitle"
  (close)="closeJsonModal()"
></app-json-modal>

// components/log-viewer.tsx
"use client"

import type React from "react"

import { useState } from "react"
import { LogModal } from "./log-modal"
import "./log-viewer.css"

export interface LogEntry {
  id: string
  timestamp: string
  method: "GET" | "POST" | "PUT" | "DELETE" | "PATCH"
  endpoint: string
  status: number
  duration: number
  request: Record<string, any>
  response: Record<string, any>
  children?: LogEntry[]
}

interface LogViewerProps {
  logs: LogEntry[]
}

export function LogViewer({ logs }: LogViewerProps) {
  const [searchQuery, setSearchQuery] = useState("")
  const [selectedLog, setSelectedLog] = useState<LogEntry | null>(null)
  const [expandedLogs, setExpandedLogs] = useState<Set<string>>(new Set())

  const getStatusBadgeClass = (status: number) => {
    if (status >= 200 && status < 300) return "status-success"
    if (status >= 400 && status < 500) return "status-warning"
    if (status >= 500) return "status-error"
    return "status-info"
  }

  const getMethodClass = (method: string) => {
    const methodMap: Record<string, string> = {
      GET: "method-get",
      POST: "method-post",
      PUT: "method-put",
      DELETE: "method-delete",
      PATCH: "method-patch",
    }
    return methodMap[method] || "method-get"
  }

  const toggleExpand = (logId: string, e: React.MouseEvent) => {
    e.stopPropagation()
    setExpandedLogs((prev) => {
      const newSet = new Set(prev)
      if (newSet.has(logId)) {
        newSet.delete(logId)
      } else {
        newSet.add(logId)
      }
      return newSet
    })
  }

  const filteredLogs = logs.filter(
    (log) =>
      log.endpoint.toLowerCase().includes(searchQuery.toLowerCase()) ||
      log.method.toLowerCase().includes(searchQuery.toLowerCase()) ||
      log.status.toString().includes(searchQuery) ||
      log.id.toLowerCase().includes(searchQuery.toLowerCase()),
  )

  const totalChildren = logs.reduce((acc, log) => acc + (log.children?.length || 0), 0)

  const renderLogItem = (log: LogEntry, isChild = false) => {
    const isExpanded = expandedLogs.has(log.id)
    const isActive = selectedLog?.id === log.id || isExpanded

    return (
      <div key={log.id} className={isChild ? "child-log-wrapper" : ""}>
        <button
          onClick={() => setSelectedLog(log)}
          className={`log-item ${isActive ? "log-item-active" : ""} ${isChild ? "log-item-child" : ""}`}
        >
          {log.children && log.children.length > 0 && (
            <svg
              className={`log-chevron ${isExpanded ? "log-chevron-expanded" : ""}`}
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              onClick={(e) => toggleExpand(log.id, e)}
            >
              <polyline points="9 18 15 12 9 6"></polyline>
            </svg>
          )}
          {(!log.children || log.children.length === 0) && (
            <svg
              className="log-chevron log-chevron-hidden"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
            >
              <polyline points="9 18 15 12 9 6"></polyline>
            </svg>
          )}

          <div className="log-details">
            <div className="log-endpoint">{log.endpoint}</div>

            <div className="log-metadata">
              <div className="metadata-item">
                <span className="metadata-label">ID:</span>
                <span className="metadata-value">{log.id}</span>
              </div>

              <div className="metadata-item">
                <span className="metadata-label">Time:</span>
                <span className="metadata-value">{log.timestamp}</span>
              </div>

              <div className="metadata-item">
                <span className="metadata-label">Method:</span>
                <span className={`metadata-badge ${getMethodClass(log.method)}`}>{log.method}</span>
              </div>

              <div className="metadata-item">
                <span className="metadata-label">Status:</span>
                <span className={`metadata-badge ${getStatusBadgeClass(log.status)}`}>{log.status}</span>
              </div>

              <div className="metadata-item">
                <span className="metadata-label">Duration:</span>
                <span className="metadata-value">{log.duration}ms</span>
              </div>
            </div>

            {log.children && log.children.length > 0 && (
              <div className="log-children-badge">
                <span className="children-count">{log.children.length}</span>
                <span className="children-text">child operation{log.children.length !== 1 ? "s" : ""}</span>
              </div>
            )}
          </div>
        </button>

        {isExpanded && log.children && log.children.length > 0 && (
          <div className="children-container">{log.children.map((child) => renderLogItem(child, true))}</div>
        )}
      </div>
    )
  }

  return (
    <div className="log-viewer">
      <div className="log-viewer-header">
        <div className="header-content">
          <h1 className="header-title">Request Logs</h1>
          <p className="header-subtitle">Monitor and investigate API request/response logs</p>
        </div>

        <div className="search-container">
          <svg className="search-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <circle cx="11" cy="11" r="8"></circle>
            <path d="m21 21-4.35-4.35"></path>
          </svg>
          <input
            type="text"
            placeholder="Search by ID, endpoint, method, or status..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="search-input"
          />
        </div>
      </div>

      <div className="stats-bar">
        <div className="stats-content">
          <span className="stat-item">
            <strong className="stat-value">{logs.length}</strong> parent logs
          </span>
          <span className="stat-item">
            <strong className="stat-value">{totalChildren}</strong> child operations
          </span>
          <span className="stat-item">
            <strong className="stat-value">{filteredLogs.length}</strong> filtered
          </span>
        </div>
      </div>

      <div className="log-list">
        <div className="log-list-content">{filteredLogs.map((log) => renderLogItem(log))}</div>

        {filteredLogs.length === 0 && <div className="empty-state">No logs found matching your search.</div>}
      </div>

      {selectedLog && <LogModal log={selectedLog} isOpen={!!selectedLog} onClose={() => setSelectedLog(null)} />}
    </div>
  )
}
